//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCryptor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelCryptor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Files.
        /// </summary>
        internal static string ActionEncodeTitle {
            get {
                return ResourceManager.GetString("ActionEncodeTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode1 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode10 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode11 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode12 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode13 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode14 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode15 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode16 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode17 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode18 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode19 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode2 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode20 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode21 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode22 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode23 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode24 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode25 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode26 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode27 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode28 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode29 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode3 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode30 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode31 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode32 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode33 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode34 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode4 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode5 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode6 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode7 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode8 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationDecode9 {
            get {
                object obj = ResourceManager.GetObject("AnimationDecode9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode1 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode10 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode11 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode12 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode13 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode14 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode15 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode16 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode17 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode18 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode19 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode2 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode20 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode21 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode22 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode23 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode24 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode25 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode26 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode27 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode28 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode29 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode3 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode30 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode31 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode32 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode33 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode34 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode4 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode5 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode6 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode7 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode8 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnimationEncode9 {
            get {
                object obj = ResourceManager.GetObject("AnimationEncode9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundAbout {
            get {
                object obj = ResourceManager.GetObject("BackgroundAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundMain {
            get {
                object obj = ResourceManager.GetObject("BackgroundMain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundWizard {
            get {
                object obj = ResourceManager.GetObject("BackgroundWizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonAddFile {
            get {
                object obj = ResourceManager.GetObject("ButtonAddFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonAddFolder {
            get {
                object obj = ResourceManager.GetObject("ButtonAddFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonBrowse {
            get {
                object obj = ResourceManager.GetObject("ButtonBrowse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonGo {
            get {
                object obj = ResourceManager.GetObject("ButtonGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNewFolder {
            get {
                object obj = ResourceManager.GetObject("ButtonNewFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRemoveSelection {
            get {
                object obj = ResourceManager.GetObject("ButtonRemoveSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DestinationFolder {
            get {
                object obj = ResourceManager.GetObject("DestinationFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageFrame {
            get {
                object obj = ResourceManager.GetObject("ImageFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageKey {
            get {
                object obj = ResourceManager.GetObject("ImageKey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageNoSelection {
            get {
                object obj = ResourceManager.GetObject("ImageNoSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo64x64 {
            get {
                object obj = ResourceManager.GetObject("Logo64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon LogoIcon {
            get {
                object obj = ResourceManager.GetObject("LogoIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainAbout {
            get {
                object obj = ResourceManager.GetObject("MainAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainDecode {
            get {
                object obj = ResourceManager.GetObject("MainDecode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainEncode {
            get {
                object obj = ResourceManager.GetObject("MainEncode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainHelp {
            get {
                object obj = ResourceManager.GetObject("MainHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelCryptor
        ///©2008 CodeGazer. All rights reserved.
        ///
        ///Command specification:
        ///pixelcryptor.exe [/codefilepath | /cf ...] [/h | /?]
        ///
        ///Command arguments:
        ////codefilepath	Preselects the codefile
        ////?		Displays this help text
        ///
        ///These switches were introduced for the file association.
        ///More options might be added to future versions..
        /// </summary>
        internal static string MsgCommandLineHelpText {
            get {
                return ResourceManager.GetString("MsgCommandLineHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelCryptor commandline arguments.
        /// </summary>
        internal static string MsgCommandLineHelpTitle {
            get {
                return ResourceManager.GetString("MsgCommandLineHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the orginal files and folders
        ///after the encoding operation?
        ///
        ///The removal is final and can&apos;t be undone..
        /// </summary>
        internal static string MsgDeleteAfterEncodeDescription {
            get {
                return ResourceManager.GetString("MsgDeleteAfterEncodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete after operation?.
        /// </summary>
        internal static string MsgDeleteAfterEncodeTitle {
            get {
                return ResourceManager.GetString("MsgDeleteAfterEncodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package you&apos;ve selected is either invalid or can not
        ///be unlocked using the image you&apos;ve specified..
        /// </summary>
        internal static string MsgInvalidPackageText {
            get {
                return ResourceManager.GetString("MsgInvalidPackageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package or image.
        /// </summary>
        internal static string MsgInvalidPackageTitle {
            get {
                return ResourceManager.GetString("MsgInvalidPackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on the program and it&apos;s creators.
        /// </summary>
        internal static string TxtActionAboutDescription {
            get {
                return ResourceManager.GetString("TxtActionAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PixelCryptor.
        /// </summary>
        internal static string TxtActionAboutTitle {
            get {
                return ResourceManager.GetString("TxtActionAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore your files and folders from a package.
        /// </summary>
        internal static string TxtActionDecodeDescription {
            get {
                return ResourceManager.GetString("TxtActionDecodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Files.
        /// </summary>
        internal static string TxtActionDecodeTitle {
            get {
                return ResourceManager.GetString("TxtActionDecodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to PixelCryptor, select one of the items above to start.
        /// </summary>
        internal static string TxtActionDefaultDescription {
            get {
                return ResourceManager.GetString("TxtActionDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelCryptor.
        /// </summary>
        internal static string TxtActionDefaultTitle {
            get {
                return ResourceManager.GetString("TxtActionDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new package in a few simple steps.
        /// </summary>
        internal static string TxtActionEncodeDescription {
            get {
                return ResourceManager.GetString("TxtActionEncodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Files.
        /// </summary>
        internal static string TxtActionEncodeTitle {
            get {
                return ResourceManager.GetString("TxtActionEncodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the PixelCryptor&apos;s Help file.
        /// </summary>
        internal static string TxtActionHelpDescription {
            get {
                return ResourceManager.GetString("TxtActionHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string TxtActionHelpTitle {
            get {
                return ResourceManager.GetString("TxtActionHelpTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ViewDetails {
            get {
                object obj = ResourceManager.GetObject("ViewDetails", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewLargeIcon {
            get {
                object obj = ResourceManager.GetObject("ViewLargeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewList {
            get {
                object obj = ResourceManager.GetObject("ViewList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewSmallIcons {
            get {
                object obj = ResourceManager.GetObject("ViewSmallIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewTiles {
            get {
                object obj = ResourceManager.GetObject("ViewTiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
